# Generated by go2rpm 1
%bcond_with check

# https://github.com/canonical/go-dqlite
%global goipath         github.com/canonical/go-dqlite
Version:                1.4.1

%gometa

%global common_description %{expand:
Go bindings for libdqlite.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go bindings for libdqlite

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/Rican7/retry)
BuildRequires:  golang(github.com/Rican7/retry/backoff)
BuildRequires:  golang(github.com/Rican7/retry/strategy)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  pkgconfig(dqlite)
BuildRequires:  pkgconfig(raft)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  sqlite-libs(wal-replication)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%global gotestflags %{gotestflags} -v -tags "libsqlite3"
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Apr 05 12:32:32 UTC 2020 Jan Pazdziora <adelton@fedoraproject.org> - 1.4.1-1
- Initial package

